# NOT NEEDED AS WE USE AN OCP ROUTE
# ingress:
  # enabled: true
  # host: idp-backstage.apps.qshift.snowdrop.dev
  # className: openshift-default
serviceAccount:
  create: true
  name: my-backstage
backstage:
  image:
    registry: "quay.io"
    repository: "ch007m/backstage-qshift-ocp"
    tag: "latest"
    pullPolicy: "Always"
  extraAppConfig:
    - filename: app-config.qshift.yaml
      configMapRef: my-app-config
postgresql:
  enabled: false