kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: idp
spec:
  host: idp-backstage.apps.qshift.snowdrop.dev
  to:
    kind: Service
    name: helm-backstage
    weight: 100
  port:
    targetPort: http-backend
  tls:
    termination: edge
  wildcardPolicy: None
