apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-backstage
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  sources:
    - # Additional resources to install and not packaged part of the backstage chart
      repoURL: 'https://github.com/q-shift/backstage-playground'
      path: manifest/backstage
    - # Helm values to be used to deploy backstage
      repoURL: 'https://github.com/q-shift/backstage-playground'
      ref: helm-values
    - chart: backstage
      repoURL: https://backstage.github.io/charts
      targetRevision: 1.8.2
      helm:
        valueFiles:
         - $helm-values/manifest/helm/values.yaml
        #values: |
        #  ingress:
        #    enabled: true
        #    host: idp-backstage.apps.qshift.snowdrop.dev
        #    className: openshift-default
        #  serviceAccount:
        #    create: true
        #    name: my-backstage
        #  backstage:
        #    image:
        #      registry: "quay.io"
        #      repository: "ch007m/backstage-qshift-ocp"
        #      tag: "latest"
        #      pullPolicy: "Always"
        #    extraAppConfig:
        #      - filename: app-config.qshift.yaml
        #        configMapRef: my-app-config
        #  postgresql:
        #    enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
